namespace Terraria.NetWork.Core.Protocol;

[Flags]
public enum PacketSupportFlags
{
    None = 0,
    InboundCodec = 1 << 0,
    OutboundCodec = 1 << 1,
    InboundFlow = 1 << 2,
    OpaqueCodec = 1 << 3
}

public sealed record PacketCatalogEntry(
    PacketType Type,
    PacketSupportFlags Support,
    string? CurrentServerTypeName = null,
    string? Notes = null)
{
    public byte MessageId => (byte)Type;
}

// PacketCatalog keeps the full legacy id table in one place. Most packets are
// still placeholders today, but the catalog prevents ids from disappearing
// from the new Server while implementation catches up.
public static class PacketCatalog
{
    public static IReadOnlyList<PacketCatalogEntry> All { get; } =
    [
        Entry(PacketType.NeverCalled),
        Entry(PacketType.Hello, PacketSupportFlags.InboundCodec | PacketSupportFlags.InboundFlow, "HelloPacketRaw"),
        Entry(PacketType.Kick, PacketSupportFlags.OutboundCodec, "DisconnectPacket"),
        Entry(PacketType.PlayerInfo, PacketSupportFlags.OutboundCodec, "HandshakeAcceptedPacket", "Legacy enum name is kept, but the current Server uses packet 3 as the handshake-accepted control packet."),
        Entry(PacketType.SyncPlayer, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec | PacketSupportFlags.InboundFlow, "PlayerInfoPacketRaw / PlayerInfoPacket"),
        Entry(PacketType.SyncEquipment, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncEquipmentPacket"),
        Entry(PacketType.RequestWorldData, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "RequestWorldDataPacket"),
        Opaque(PacketType.WorldData, "WorldDataPacket7"),
        Entry(PacketType.SpawnTileData, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SpawnTileDataPacket"),
        Opaque(PacketType.StatusTextSize, "StatusTextSizePacket9"),
        Opaque(PacketType.TileSection, "TileSectionPacket10"),
        Entry(PacketType.TileFrameSection, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "TileFrameSectionPacket"),
        Entry(PacketType.PlayerSpawn, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "PlayerSpawnPacket"),
        Entry(PacketType.PlayerControls, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "PlayerControlsPacket13"),
        Opaque(PacketType.PlayerActive, "PlayerActivePacket14"),
        Opaque(PacketType.Unused15, "UnusedPacket15", "Deprecated legacy packet id. Kept only for packet-table completeness."),
        Opaque(PacketType.PlayerHealth, "PlayerHealthPacket16"),
        Opaque(PacketType.TileManipulation, "TileManipulationPacket17"),
        Opaque(PacketType.SetTime, "SetTimePacket18"),
        Opaque(PacketType.ToggleDoorState, "ToggleDoorStatePacket19"),
        Entry(PacketType.AreaTileChange, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "AreaTileChangePacket"),
        Opaque(PacketType.SyncItem, "SyncItemPacket21"),
        Opaque(PacketType.ItemOwner, "ItemOwnerPacket22"),
        Entry(PacketType.SyncNPC, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncNpcPacket23"),
        Opaque(PacketType.PlayerStrike, "PlayerStrikePacket24"),
        Opaque(PacketType.ObsoleteChatMessage, "ObsoleteChatMessagePacket25", "Deprecated legacy packet id. Kept only for backward packet-table compatibility."),
        Opaque(PacketType.ObsoletePlayerHurt, "ObsoletePlayerHurtPacket26", "Deprecated legacy packet id. Kept only for backward packet-table compatibility."),
        Entry(PacketType.SyncProjectile, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncProjectilePacket27"),
        Entry(PacketType.DamageNPC, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "DamageNpcPacket"),
        Entry(PacketType.KillProjectile, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "KillProjectilePacket"),
        Opaque(PacketType.TogglePVP, "TogglePvpPacket30"),
        Opaque(PacketType.RequestChestOpen, "RequestChestOpenPacket31"),
        Opaque(PacketType.SyncChestItem, "SyncChestItemPacket32"),
        Entry(PacketType.SyncPlayerChest, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncPlayerChestPacket"),
        Opaque(PacketType.ChestUpdates, "ChestUpdatesPacket34"),
        Opaque(PacketType.PlayerHeal, "PlayerHealPacket35"),
        Opaque(PacketType.SyncPlayerZone, "SyncPlayerZonePacket36"),
        Entry(PacketType.RequestPassword, PacketSupportFlags.OutboundCodec, "PasswordRequestPacket"),
        Entry(PacketType.SendPassword, PacketSupportFlags.InboundCodec | PacketSupportFlags.InboundFlow, "PasswordPacketRaw"),
        Opaque(PacketType.ReleaseItemOwnership, "ReleaseItemOwnershipPacket39"),
        Opaque(PacketType.SyncTalkNPC, "SyncTalkNpcPacket40"),
        Opaque(PacketType.ItemRotationAndAnimation, "ItemRotationAndAnimationPacket41"),
        Opaque(PacketType.PlayerMana, "PlayerManaPacket42"),
        Opaque(PacketType.ManaEffect, "ManaEffectPacket43"),
        Opaque(PacketType.PlayerHurtOld, "PlayerHurtOldPacket44"),
        Opaque(PacketType.TeamChange, "TeamChangePacket45"),
        Opaque(PacketType.OpenSignRequest, "OpenSignRequestPacket46"),
        Opaque(PacketType.OpenSignResponse, "OpenSignResponsePacket47"),
        Opaque(PacketType.LiquidUpdate, "LiquidUpdatePacket48"),
        Opaque(PacketType.InitialSpawn, "InitialSpawnPacket49"),
        Opaque(PacketType.PlayerBuffs, "PlayerBuffsPacket50"),
        Opaque(PacketType.AssortmentOfSomething, "AssortmentOfSomethingPacket51"),
        Opaque(PacketType.Unlock, "UnlockPacket52"),
        Opaque(PacketType.AddNPCBuff, "AddNpcBuffPacket53"),
        Opaque(PacketType.SendNPCBuffs, "SendNpcBuffsPacket54"),
        Opaque(PacketType.AddPlayerBuff, "AddPlayerBuffPacket55"),
        Opaque(PacketType.UpdateNPCName, "UpdateNpcNamePacket56"),
        Opaque(PacketType.UpdateGoodEvil, "UpdateGoodEvilPacket57"),
        Opaque(PacketType.PlayHarp, "PlayHarpPacket58"),
        Opaque(PacketType.HitSwitch, "HitSwitchPacket59"),
        Opaque(PacketType.UpdateNPCHome, "UpdateNpcHomePacket60"),
        Opaque(PacketType.SpawnBossUseLicenseStartEvent, "SpawnBossUseLicenseStartEventPacket61"),
        Opaque(PacketType.PlayerDodge, "PlayerDodgePacket62"),
        Opaque(PacketType.SyncTilePaintOrCoating, "SyncTilePaintOrCoatingPacket63"),
        Opaque(PacketType.SyncWallPaintOrCoating, "SyncWallPaintOrCoatingPacket64"),
        Opaque(PacketType.TeleportEntity, "TeleportEntityPacket65"),
        Opaque(PacketType.PlayerHealOther, "PlayerHealOtherPacket66"),
        Opaque(PacketType.Unused67, "UnusedPacket67", "Deprecated legacy packet id. Kept only for packet-table completeness."),
        Opaque(PacketType.ClientUUID, "ClientUuidPacket68"),
        Opaque(PacketType.ChestName, "ChestNamePacket69"),
        Opaque(PacketType.BugCatching, "BugCatchingPacket70"),
        Opaque(PacketType.BugReleasing, "BugReleasingPacket71"),
        Opaque(PacketType.TravelMerchantItems, "TravelMerchantItemsPacket72"),
        Opaque(PacketType.RequestTeleportationByServer, "RequestTeleportationByServerPacket73"),
        Opaque(PacketType.AnglerQuest, "AnglerQuestPacket74"),
        Opaque(PacketType.AnglerQuestFinished, "AnglerQuestFinishedPacket75"),
        Opaque(PacketType.QuestsCountSync, "QuestsCountSyncPacket76"),
        Opaque(PacketType.TemporaryAnimation, "TemporaryAnimationPacket77"),
        Opaque(PacketType.InvasionProgressReport, "InvasionProgressReportPacket78"),
        Opaque(PacketType.PlaceObject, "PlaceObjectPacket79"),
        Opaque(PacketType.SyncPlayerChestIndex, "SyncPlayerChestIndexPacket80"),
        Opaque(PacketType.CombatTextInt, "CombatTextIntPacket81"),
        Entry(PacketType.NetModules, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "NetModulesPacket"),
        Opaque(PacketType.Unused83, "UnusedPacket83", "Deprecated legacy packet id. Kept only for packet-table completeness."),
        Opaque(PacketType.PlayerStealth, "PlayerStealthPacket84"),
        Entry(PacketType.QuickStackChests, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "QuickStackChestsPacket"),
        Entry(PacketType.TileEntitySharing, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "TileEntitySharingPacket"),
        Opaque(PacketType.TileEntityPlacement, "TileEntityPlacementPacket87"),
        Entry(PacketType.ItemTweaker, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "ItemTweakerPacket"),
        Opaque(PacketType.ItemFrameTryPlacing, "ItemFrameTryPlacingPacket89"),
        Opaque(PacketType.InstancedItem, "InstancedItemPacket90"),
        Entry(PacketType.SyncEmoteBubble, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncEmoteBubblePacket91"),
        Opaque(PacketType.SyncExtraValue, "SyncExtraValuePacket92"),
        Entry(PacketType.SocialHandshake, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SocialHandshakePacket"),
        Entry(PacketType.DevCommands, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "DevCommandsPacket94"),
        Opaque(PacketType.MurderSomeoneElsesPortal, "MurderSomeoneElsesPortalPacket95"),
        Opaque(PacketType.TeleportPlayerThroughPortal, "TeleportPlayerThroughPortalPacket96"),
        Opaque(PacketType.AchievementMessageNPCKilled, "AchievementMessageNpcKilledPacket97"),
        Opaque(PacketType.AchievementMessageEventHappened, "AchievementMessageEventHappenedPacket98"),
        Opaque(PacketType.MinionRestTargetUpdate, "MinionRestTargetUpdatePacket99"),
        Opaque(PacketType.TeleportNPCThroughPortal, "TeleportNpcThroughPortalPacket100"),
        Opaque(PacketType.UpdateTowerShieldStrengths, "UpdateTowerShieldStrengthsPacket101"),
        Opaque(PacketType.NebulaLevelupRequest, "NebulaLevelupRequestPacket102"),
        Opaque(PacketType.MoonlordHorror, "MoonlordHorrorPacket103"),
        Entry(PacketType.ShopOverride, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "ShopOverridePacket"),
        Opaque(PacketType.GemLockToggle, "GemLockTogglePacket105"),
        Entry(PacketType.PoofOfSmoke, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "PoofOfSmokePacket106"),
        Entry(PacketType.SmartTextMessage, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SmartTextMessagePacket107"),
        Entry(PacketType.WiredCannonShot, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "WiredCannonShotPacket"),
        Opaque(PacketType.MassWireOperation, "MassWireOperationPacket109"),
        Opaque(PacketType.MassWireOperationPay, "MassWireOperationPayPacket110"),
        Opaque(PacketType.ToggleParty, "TogglePartyPacket111"),
        Opaque(PacketType.SpecialFX, "SpecialFxPacket112"),
        Opaque(PacketType.CrystalInvasionStart, "CrystalInvasionStartPacket113"),
        Opaque(PacketType.CrystalInvasionWipeAllTheThingsss, "CrystalInvasionWipeAllTheThingsssPacket114"),
        Opaque(PacketType.MinionAttackTargetUpdate, "MinionAttackTargetUpdatePacket115"),
        Entry(PacketType.CrystalInvasionSendWaitTime, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "CrystalInvasionSendWaitTimePacket"),
        Entry(PacketType.PlayerHurtV2, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "PlayerHurtV2Packet"),
        Entry(PacketType.PlayerDeathV2, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "PlayerDeathV2Packet"),
        Entry(PacketType.CombatTextString, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "CombatTextStringPacket"),
        Opaque(PacketType.Emoji, "EmojiPacket120"),
        Entry(PacketType.TEDisplayDollDataSync, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "TeDisplayDollDataSyncPacket"),
        Opaque(PacketType.RequestTileEntityInteraction, "RequestTileEntityInteractionPacket122"),
        Opaque(PacketType.WeaponsRackTryPlacing, "WeaponsRackTryPlacingPacket123"),
        Entry(PacketType.TEHatRackItemSync, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "TeHatRackItemSyncPacket"),
        Opaque(PacketType.SyncTilePicking, "SyncTilePickingPacket125"),
        Entry(PacketType.SyncRevengeMarker, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncRevengeMarkerPacket"),
        Opaque(PacketType.RemoveRevengeMarker, "RemoveRevengeMarkerPacket127"),
        Opaque(PacketType.LandGolfBallInCup, "LandGolfBallInCupPacket128"),
        Opaque(PacketType.FinishedConnectingToServer, "FinishedConnectingToServerPacket129", "This is the natural transition point for a future explicit WorldSyncCompleted event."),
        Entry(PacketType.FishOutNPC, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "FishOutNpcPacket"),
        Entry(PacketType.TamperWithNPC, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "TamperWithNpcPacket"),
        Entry(PacketType.PlayLegacySound, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "PlayLegacySoundPacket132"),
        Entry(PacketType.FoodPlatterTryPlacing, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "FoodPlatterTryPlacingPacket"),
        Entry(PacketType.UpdatePlayerLuckFactors, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "UpdatePlayerLuckFactorsPacket"),
        Entry(PacketType.DeadPlayer, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "DeadPlayerPacket"),
        Entry(PacketType.SyncCavernMonsterType, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncCavernMonsterTypePacket"),
        Entry(PacketType.RequestNPCBuffRemoval, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "RequestNpcBuffRemovalPacket"),
        Entry(PacketType.ClientSyncedInventory, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "ClientSyncedInventoryPacket"),
        Entry(PacketType.SetCountsAsHostForGameplay, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SetCountsAsHostForGameplayPacket"),
        Entry(PacketType.SetMiscEventValues, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SetMiscEventValuesPacket"),
        Entry(PacketType.RequestLucyPopup, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "RequestLucyPopupPacket"),
        Entry(PacketType.SyncProjectileTrackers, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncProjectileTrackersPacket142"),
        Entry(PacketType.CrystalInvasionRequestedToSkipWaitTime, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "CrystalInvasionRequestedToSkipWaitTimePacket"),
        Entry(PacketType.RequestQuestEffect, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "RequestQuestEffectPacket"),
        Entry(PacketType.SyncItemsWithShimmer, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncItemsWithShimmerPacket145"),
        Entry(PacketType.ShimmerActions, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "ShimmerActionsPacket146"),
        Entry(PacketType.SyncLoadout, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncLoadoutPacket"),
        Entry(PacketType.SyncItemCannotBeTakenByEnemies, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncItemCannotBeTakenByEnemiesPacket148"),
        Entry(PacketType.DeadCellsDisplayJarTryPlacing, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "DeadCellsDisplayJarTryPlacingPacket"),
        Entry(PacketType.SpectatePlayer, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SpectatePlayerPacket"),
        Entry(PacketType.SyncItemDespawn, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncItemDespawnPacket151"),
        Entry(PacketType.ItemUseSound, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "ItemUseSoundPacket"),
        Entry(PacketType.NPCDebuffDamage, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "NpcDebuffDamagePacket"),
        Entry(PacketType.Ping, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "PingPacket"),
        Entry(PacketType.SyncChestSize, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "SyncChestSizePacket"),
        Entry(PacketType.TELeashedEntityAnchorPlaceItem, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "TeLeashedEntityAnchorPlaceItemPacket"),
        Entry(PacketType.TeamChangeFromUI, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "TeamChangeFromUiPacket"),
        Entry(PacketType.ExtraSpawnSectionLoaded, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "ExtraSpawnSectionLoadedPacket"),
        Entry(PacketType.RequestSection, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "RequestSectionPacket"),
        Entry(PacketType.ItemPosition, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "ItemPositionPacket"),
        Entry(PacketType.HostToken, PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec, "HostTokenPacket")
    ];

    public static PacketCatalogEntry Get(PacketType type) => All[(byte)type];

    public static PacketCatalogEntry Get(byte messageId) => All[messageId];

    private static PacketCatalogEntry Entry(
        PacketType type,
        PacketSupportFlags support = PacketSupportFlags.None,
        string? currentServerTypeName = null,
        string? notes = null)
    {
        return new PacketCatalogEntry(type, support, currentServerTypeName, notes);
    }

    private static PacketCatalogEntry Opaque(PacketType type, string currentServerTypeName, string? notes = null)
    {
        return Entry(
            type,
            PacketSupportFlags.InboundCodec | PacketSupportFlags.OutboundCodec | PacketSupportFlags.OpaqueCodec,
            currentServerTypeName,
            notes);
    }
}
