using System.Numerics;
using Terraria.NetWork.Core.Protocol;

namespace Terraria.NetWork.Prototype.TypedSpanSourceGen;

public sealed class SmokePacket
{
    public BitsByte Flags { get; set; }

    public short ItemId { get; set; }

    public ushort? Damage { get; set; }
}

[ConceptPacketSource(
    PacketType.ItemTweaker,
    typeof(SmokePacket),
    "SmokePacketGeneratedCodec",
    "SmokePacketGeneratedDefinition")]
public sealed class SmokePacketSpec
{
    [ConceptPacketField(0)]
    [ConceptBit(0, "HasDamage")]
    public BitsByte Flags { get; set; }

    [ConceptPacketField(1)]
    public short ItemId { get; set; }

    [ConceptPacketField(2, PacketFieldKind.Variable)]
    [ConceptFlagCondition(nameof(Flags), 0)]
    public ushort? Damage { get; set; }
}

internal static class Program
{
    private static int Main()
    {
        var packet = new SmokePacket
        {
            Flags = new BitsByte(true),
            ItemId = 88,
            Damage = 321
        };

        var bytes = SmokePacketGeneratedCodec.Serialize(packet);
        var expected = new byte[] { (byte)PacketType.ItemTweaker, 0x01, 0x58, 0x00, 0x41, 0x01 };
        if (!bytes.AsSpan().SequenceEqual(expected))
        {
            throw new InvalidOperationException(
                $"Unexpected generated bytes. Expected={BitConverter.ToString(expected)}, Actual={BitConverter.ToString(bytes)}");
        }

        var roundTrip = SmokePacketGeneratedCodec.Deserialize(bytes, out var consumed);
        if (consumed != bytes.Length || roundTrip.ItemId != packet.ItemId || roundTrip.Damage != packet.Damage)
        {
            throw new InvalidOperationException("Generated codec round-trip did not preserve the packet.");
        }

        var definitionBytes = PacketCodec.Write(SmokePacketGeneratedDefinition.Instance, packet);
        if (!definitionBytes.AsSpan().SequenceEqual(bytes))
        {
            throw new InvalidOperationException("Generated definition did not consume the generated codec consistently.");
        }

        Console.WriteLine("Typed span source generator smoke passed.");
        return 0;
    }
}
