using System.Text;

namespace Terraria.NetWork.Concept;

// 第一阶段只生成标量字段与 PacketCondition 控制的可选字段。
public static class PacketGraphCodecEmitter
{
    public static string WriteToDirectory(PacketGraphManifest manifest, string outputDirectory)
    {
        ArgumentNullException.ThrowIfNull(manifest);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputDirectory);

        Directory.CreateDirectory(outputDirectory);
        var outputPath = Path.Combine(
            outputDirectory,
            $"{GetCodecName(manifest.RuntimePacketType, manifest.MessageId)}.g.cs");
        Write(manifest, outputPath);
        return outputPath;
    }

    public static void Write(PacketGraphManifest manifest, string outputPath)
    {
        ArgumentNullException.ThrowIfNull(manifest);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputPath);
        File.WriteAllText(outputPath, Emit(manifest));
    }

    public static string Emit(PacketGraphManifest manifest)
    {
        ArgumentNullException.ThrowIfNull(manifest);

        var runtimeType = manifest.RuntimePacketType;
        if (string.IsNullOrWhiteSpace(runtimeType.Namespace) || string.IsNullOrWhiteSpace(runtimeType.FullName))
        {
            throw new ArgumentException("The runtime packet type must have a namespace and full name.", nameof(manifest));
        }

        var fields = manifest.Fields.OrderBy(static field => field.Order).ToArray();
        ValidateFieldOrders(fields);
        var fieldsByOrder = fields.ToDictionary(static field => field.Order);
        var conditions = BuildConditions(manifest.Dependencies, fieldsByOrder);
        var packetTypeName = $"global::{runtimeType.FullName}";
        var codecName = GetCodecName(runtimeType, manifest.MessageId);
        var source = new StringBuilder();

        source.AppendLine("// <auto-generated by PacketGraphCodecEmitter/>");
        source.AppendLine($"namespace {runtimeType.Namespace};");
        source.AppendLine();
        source.AppendLine($"public static class {codecName}");
        source.AppendLine("{");
        source.AppendLine($"    public const byte MessageId = {manifest.MessageId};");
        source.AppendLine();
        source.AppendLine($"    public static byte[] Serialize({packetTypeName} packet)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(packet);");
        source.AppendLine("        using var stream = new global::System.IO.MemoryStream();");
        source.AppendLine("        using var writer = new global::System.IO.BinaryWriter(stream, global::System.Text.Encoding.UTF8, leaveOpen: true);");
        source.AppendLine("        writer.Write(MessageId);");
        foreach (var field in fields)
        {
            AppendConditionalWrite(source, field, conditions, fieldsByOrder);
        }
        source.AppendLine("        writer.Flush();");
        source.AppendLine("        return stream.ToArray();");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine($"    public static {packetTypeName} Deserialize(byte[] source)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(source);");
        source.AppendLine("        using var stream = new global::System.IO.MemoryStream(source, writable: false);");
        source.AppendLine("        using var reader = new global::System.IO.BinaryReader(stream, global::System.Text.Encoding.UTF8, leaveOpen: true);");
        source.AppendLine("        if (reader.ReadByte() != MessageId) throw new global::System.IO.InvalidDataException(\"Unexpected message id.\");");
        source.AppendLine($"        var packet = new {packetTypeName}();");
        foreach (var field in fields)
        {
            AppendConditionalRead(source, field, conditions, fieldsByOrder);
        }
        source.AppendLine("        if (stream.Position != stream.Length) throw new global::System.IO.InvalidDataException(\"Packet was not fully consumed.\");");
        source.AppendLine("        return packet;");
        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    private static Dictionary<int, PacketGraphDependency[]> BuildConditions(
        IReadOnlyList<PacketGraphDependency> dependencies,
        IReadOnlyDictionary<int, PacketGraphField> fieldsByOrder)
    {
        foreach (var dependency in dependencies)
        {
            if (dependency.EdgeType is not PacketEdgeType.Condition)
            {
                throw new NotSupportedException($"Codec generation does not support '{dependency.EdgeType}' dependencies.");
            }
            if (dependency.Condition is null ||
                !fieldsByOrder.TryGetValue(dependency.SourceOrder, out var source) ||
                !fieldsByOrder.ContainsKey(dependency.TargetOrder) ||
                dependency.SourceOrder >= dependency.TargetOrder)
            {
                throw new InvalidOperationException("A condition dependency must reference an earlier declared source field.");
            }
            if (dependency.Condition.Accessor is PacketConditionIndex &&
                (source.WirePrimitive != PacketWirePrimitive.BitsByte || dependency.Condition.ValueType != typeof(bool)))
            {
                throw new InvalidOperationException("An indexed condition must compare a BitsByte source to a Boolean value.");
            }
            if (dependency.Condition.Accessor is PacketConditionValue &&
                (Nullable.GetUnderlyingType(source.ValueType) ?? source.ValueType) !=
                (Nullable.GetUnderlyingType(dependency.Condition.ValueType) ?? dependency.Condition.ValueType))
            {
                throw new InvalidOperationException("A value condition must compare values of the same type.");
            }
        }

        return dependencies
            .GroupBy(static dependency => dependency.TargetOrder)
            .ToDictionary(static group => group.Key, static group => group.ToArray());
    }

    private static void ValidateFieldOrders(IReadOnlyList<PacketGraphField> fields)
    {
        if (fields.Select(static field => field.Order).Distinct().Count() != fields.Count)
        {
            throw new ArgumentException("Manifest field orders must be unique.");
        }
    }

    private static void AppendConditionalWrite(
        StringBuilder source,
        PacketGraphField field,
        IReadOnlyDictionary<int, PacketGraphDependency[]> conditions,
        IReadOnlyDictionary<int, PacketGraphField> fieldsByOrder)
    {
        AppendConditional(source, field, conditions, fieldsByOrder, WriteStatement(field), 8);
    }

    private static void AppendConditionalRead(
        StringBuilder source,
        PacketGraphField field,
        IReadOnlyDictionary<int, PacketGraphDependency[]> conditions,
        IReadOnlyDictionary<int, PacketGraphField> fieldsByOrder)
    {
        AppendConditional(source, field, conditions, fieldsByOrder, $"packet.{field.MemberName} = {ReadExpression(field)};", 8);
    }

    private static void AppendConditional(
        StringBuilder source,
        PacketGraphField field,
        IReadOnlyDictionary<int, PacketGraphDependency[]> conditions,
        IReadOnlyDictionary<int, PacketGraphField> fieldsByOrder,
        string statement,
        int indent)
    {
        if (!conditions.TryGetValue(field.Order, out var dependencies))
        {
            source.AppendLine($"{new string(' ', indent)}{statement}");
            return;
        }

        var condition = string.Join(" && ", dependencies.Select(dependency =>
            FormatCondition(dependency, fieldsByOrder[dependency.SourceOrder])));
        source.AppendLine($"{new string(' ', indent)}if ({condition})");
        source.AppendLine($"{new string(' ', indent)}{{");
        source.AppendLine($"{new string(' ', indent + 4)}{statement}");
        source.AppendLine($"{new string(' ', indent)}}}");

    }

    private static string FormatCondition(PacketGraphDependency dependency, PacketGraphField source)
    {
        var condition = dependency.Condition!;
        var sourceValue = condition.Accessor switch
        {
            PacketConditionValue => $"packet.{source.MemberName}",
            PacketConditionIndex index => $"packet.{source.MemberName}[{index.Index}]",
            _ => throw new NotSupportedException($"Codec generation does not support condition accessor '{condition.Accessor.GetType().Name}'.")
        };
        var comparison = condition.Comparison switch
        {
            PacketComparison.Equal => "==",
            PacketComparison.NotEqual => "!=",
            PacketComparison.GreaterThan => ">",
            PacketComparison.GreaterThanOrEqual => ">=",
            PacketComparison.LessThan => "<",
            PacketComparison.LessThanOrEqual => "<=",
            _ => throw new NotSupportedException($"Codec generation does not support comparison '{condition.Comparison}'.")
        };
        return $"{sourceValue} {comparison} {FormatLiteral(condition.Value, condition.ValueType)}";
    }

    private static string FormatLiteral(object? value, Type valueType)
    {
        if (value is null)
        {
            return "null";
        }

        var type = Nullable.GetUnderlyingType(valueType) ?? valueType;
        if (type == typeof(bool)) return (bool)value ? "true" : "false";
        if (type == typeof(string)) return $"\"{((string)value).Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
        if (type == typeof(byte)) return ((byte)value).ToString(System.Globalization.CultureInfo.InvariantCulture);
        if (type == typeof(short)) return ((short)value).ToString(System.Globalization.CultureInfo.InvariantCulture);
        if (type == typeof(ushort)) return ((ushort)value).ToString(System.Globalization.CultureInfo.InvariantCulture);
        if (type == typeof(uint)) return ((uint)value).ToString(System.Globalization.CultureInfo.InvariantCulture) + "u";
        if (type == typeof(float)) return ((float)value).ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "f";
        if (type.IsEnum) return $"global::{type.FullName}.{value}";

        throw new NotSupportedException($"Codec generation cannot express a comparison value of type '{valueType}'.");
    }

    private static string WriteStatement(PacketGraphField field)
    {
        var value = Nullable.GetUnderlyingType(field.ValueType) is null
            ? $"packet.{field.MemberName}"
            : $"packet.{field.MemberName}.GetValueOrDefault()";
        return field.WirePrimitive switch
        {
            PacketWirePrimitive.Byte => $"writer.Write({value});",
            PacketWirePrimitive.BitsByte => $"writer.Write((byte){value});",
            PacketWirePrimitive.Boolean => $"writer.Write({value});",
            PacketWirePrimitive.Int16 => $"writer.Write({value});",
            PacketWirePrimitive.UInt16 => $"writer.Write({value});",
            PacketWirePrimitive.UInt32 => $"writer.Write({value});",
            PacketWirePrimitive.Single => $"writer.Write({value});",
            PacketWirePrimitive.Vector2 => $"writer.Write({value}.X); writer.Write({value}.Y);",
            _ => throw new NotSupportedException($"Codec generation does not support '{field.WirePrimitive}'.")
        };
    }

    private static string ReadExpression(PacketGraphField field) => field.WirePrimitive switch
    {
        PacketWirePrimitive.Byte => "reader.ReadByte()",
        PacketWirePrimitive.BitsByte => "(global::Terraria.NetWork.Core.Protocol.BitsByte)reader.ReadByte()",
        PacketWirePrimitive.Boolean => "reader.ReadBoolean()",
        PacketWirePrimitive.Int16 => "reader.ReadInt16()",
        PacketWirePrimitive.UInt16 => "reader.ReadUInt16()",
        PacketWirePrimitive.UInt32 => "reader.ReadUInt32()",
        PacketWirePrimitive.Single => "reader.ReadSingle()",
        PacketWirePrimitive.Vector2 => "new global::System.Numerics.Vector2(reader.ReadSingle(), reader.ReadSingle())",
        _ => throw new NotSupportedException($"Codec generation does not support '{field.WirePrimitive}'.")
    };

    private static string GetCodecName(Type runtimeType, byte messageId)
    {
        var suffix = messageId.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var baseName = runtimeType.Name.EndsWith(suffix, StringComparison.Ordinal)
            ? runtimeType.Name
            : runtimeType.Name + suffix;
        return baseName + "GeneratedCodec";
    }
}
