using System.Text;
using System.Text.Json;
using Terraria.NetWork.Concept;

namespace Terraria.NetWork.Concept.GraphExporter;

internal static class GraphCodecEmitter
{
    public static void Export(IReadOnlyList<PacketGraphManifest> manifests, string outputDirectory)
    {
        ArgumentNullException.ThrowIfNull(manifests);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputDirectory);

        Directory.CreateDirectory(outputDirectory);
        foreach (var staleSource in Directory.EnumerateFiles(outputDirectory, "*GeneratedCodec.g.cs"))
        {
            File.Delete(staleSource);
        }
        var ordered = manifests.OrderBy(static manifest => manifest.MessageId).ToArray();
        var options = new JsonSerializerOptions { WriteIndented = true };
        var serializableManifest = ordered.Select(manifest => new
        {
            manifest.MessageId,
            RuntimePacketType = manifest.RuntimePacketType.FullName,
            Fields = manifest.Fields.Select(field => new
            {
                field.Order,
                field.Name,
                ValueType = field.ValueType.FullName,
                field.Kind,
                field.WirePrimitive,
                field.Conditions
            })
        });
        File.WriteAllText(Path.Combine(outputDirectory, "PacketGraphManifest.json"), JsonSerializer.Serialize(serializableManifest, options));

        foreach (var manifest in ordered)
        {
            File.WriteAllText(
                Path.Combine(outputDirectory, $"{GetGeneratedBaseName(manifest)}GeneratedCodec.g.cs"),
                EmitCodec(manifest));
        }
    }

    private static string EmitCodec(PacketGraphManifest manifest)
    {
        var typeName = $"global::{manifest.RuntimePacketType.FullName}";
        var generatedBaseName = GetGeneratedBaseName(manifest);
        var codecName = $"{generatedBaseName}GeneratedCodec";
        var definitionName = $"{generatedBaseName}GeneratedDefinition";
        var fields = manifest.Fields.OrderBy(static field => field.Order).ToArray();
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by NetWork.Concept.GraphExporter/>");
        builder.AppendLine($"namespace {manifest.RuntimePacketType.Namespace};");
        builder.AppendLine();
        builder.AppendLine($"public static class {codecName}");
        builder.AppendLine("{");
        builder.AppendLine($"    public const byte MessageId = (byte){manifest.MessageId};");
        builder.AppendLine($"    public const int MaxEncodedLength = {manifest.MaxEncodedLength};");
        builder.AppendLine();
        builder.AppendLine($"    public static int GetEncodedLength({typeName} packet)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(packet);");
        builder.AppendLine("        return GetEncodedLengthCore(packet);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public static byte[] Serialize({typeName} packet)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(packet);");
        builder.AppendLine("        var bytes = new byte[GetEncodedLengthCore(packet)];");
        builder.AppendLine("        SerializeCore(packet, bytes, out _);");
        builder.AppendLine("        return bytes;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public static void Serialize({typeName} packet, global::System.Span<byte> destination, out int written)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(packet);");
        builder.AppendLine("        var requiredLength = GetEncodedLengthCore(packet);");
        builder.AppendLine("        if (destination.Length < requiredLength) throw new global::System.ArgumentException(\"Destination span is too small.\", nameof(destination));");
        builder.AppendLine("        SerializeCore(packet, destination, out written);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public static void Serialize({typeName} packet, global::System.Buffers.IBufferWriter<byte> destination)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(packet);");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(destination);");
        builder.AppendLine("        SerializeCore(packet, destination.GetSpan(MaxEncodedLength), out var written);");
        builder.AppendLine("        destination.Advance(written);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    internal static int GetEncodedLengthCore({typeName} packet)");
        builder.AppendLine("    {");
        AppendFlagLocals(builder, fields, 8);
        builder.AppendLine("        var length = 1;");
        foreach (var field in fields)
        {
            AppendConditional(builder, ConditionExpression(field, useLocalFlags: true), 8, $"length += {field.MaxEncodedLength};");
        }
        AppendRepeatedLength(builder, manifest.RepeatedFields);
        builder.AppendLine("        return length;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    internal static void SerializeCore({typeName} packet, global::System.Span<byte> destination, out int written)");
        builder.AppendLine("    {");
        AppendFlagLocals(builder, fields, 8);
        builder.AppendLine("        var offset = 0;");
        builder.AppendLine("        WriteByte(destination, ref offset, MessageId);");
        foreach (var field in fields)
        {
            AppendConditional(builder, ConditionExpression(field, useLocalFlags: true), 8, GetWriteStatement(field));
        }
        AppendRepeatedWrites(builder, manifest.RepeatedFields);
        builder.AppendLine("        written = offset;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public static {typeName} Deserialize(byte[] source)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(source);");
        builder.AppendLine("        return Deserialize(source.AsSpan(), out _);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public static {typeName} Deserialize(global::System.ReadOnlySpan<byte> source, out int consumed)");
        builder.AppendLine("    {");
        builder.AppendLine("        var offset = 0;");
        builder.AppendLine("        if (ReadByte(source, ref offset) != MessageId) throw new global::System.IO.InvalidDataException(\"Unexpected message id.\");");
        builder.AppendLine($"        var packet = new {typeName}();");
        foreach (var field in fields)
        {
            var readStatement = $"packet.{field.Name} = {GetReadExpression(field)};";
            var condition = ConditionExpression(field, useLocalFlags: false);
            if (condition is null)
            {
                builder.AppendLine($"        {readStatement}");
                continue;
            }
            builder.AppendLine($"        if ({condition})");
            builder.AppendLine("        {");
            builder.AppendLine($"            {readStatement}");
            builder.AppendLine("        }");
            builder.AppendLine("        else");
            builder.AppendLine("        {");
            builder.AppendLine($"            packet.{field.Name} = default;");
            builder.AppendLine("        }");
        }
        AppendRepeatedReads(builder, manifest.RepeatedFields);
        builder.AppendLine("        if (offset != source.Length) throw new global::System.IO.InvalidDataException(\"Packet was not fully consumed.\");");
        builder.AppendLine("        consumed = offset;");
        builder.AppendLine("        return packet;");
        builder.AppendLine("    }");
        AppendPrimitiveHelpers(builder);
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine($"internal static class {definitionName}");
        builder.AppendLine("{");
        builder.AppendLine("    private sealed class Codec : global::Terraria.NetWork.Core.Protocol.IPacketCustomCodec<" + typeName + ">");
        builder.AppendLine("    {");
        builder.AppendLine("        public byte[] Write(global::Terraria.NetWork.Core.Protocol.PacketDefinition<" + typeName + "> definition, " + typeName + " packet) => " + codecName + ".Serialize(packet);");
        builder.AppendLine("        public " + typeName + " Read(global::Terraria.NetWork.Core.Protocol.PacketDefinition<" + typeName + "> definition, byte[] bytes) => " + codecName + ".Deserialize(bytes);");
        builder.AppendLine("        public void ValidatePacket(global::Terraria.NetWork.Core.Protocol.PacketDefinition<" + typeName + "> definition, " + typeName + " packet) { }");
        builder.AppendLine("    }");
        builder.AppendLine("    public static global::Terraria.NetWork.Core.Protocol.PacketDefinition<" + typeName + "> Instance { get; } = new global::Terraria.NetWork.Core.Protocol.PacketDefinitionBuilder<" + typeName + ">().Build(" + codecName + ".MessageId, new Codec());");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendRepeatedLength(StringBuilder builder, IReadOnlyList<PacketGraphRepeatedField> repeatedFields)
    {
        foreach (var repeated in repeatedFields)
        {
            builder.AppendLine($"        foreach (var tile in packet.{repeated.Name})");
            builder.AppendLine("        {");
            AppendElementFlagLocals(builder, repeated.Fields, 12);
            foreach (var field in repeated.Fields)
                AppendConditional(builder, ElementConditionExpression(field, true), 12, $"length += {field.MaxEncodedLength};");
            builder.AppendLine("        }");
        }
    }

    private static void AppendRepeatedWrites(StringBuilder builder, IReadOnlyList<PacketGraphRepeatedField> repeatedFields)
    {
        foreach (var repeated in repeatedFields)
        {
            builder.AppendLine($"        foreach (var tile in packet.{repeated.Name})");
            builder.AppendLine("        {");
            AppendElementFlagLocals(builder, repeated.Fields, 12);
            foreach (var field in repeated.Fields)
                AppendConditional(builder, ElementConditionExpression(field, true), 12, GetWriteStatement(field, "tile"));
            builder.AppendLine("        }");
        }
    }

    private static void AppendRepeatedReads(StringBuilder builder, IReadOnlyList<PacketGraphRepeatedField> repeatedFields)
    {
        foreach (var repeated in repeatedFields)
        {
            var elementType = $"global::{repeated.ElementType.FullName}";
            var dimensions = string.Join(" * ", repeated.DimensionFieldNames.Select(name => $"packet.{name}"));
            builder.AppendLine($"        var recordCount = {dimensions};");
            builder.AppendLine($"        packet.{repeated.Name} = new {elementType}[recordCount];");
            builder.AppendLine("        for (var recordIndex = 0; recordIndex < recordCount; recordIndex++)");
            builder.AppendLine("        {");
            builder.AppendLine($"            var tile = new {elementType}();");
            foreach (var field in repeated.Fields)
            {
                var assignment = $"tile.{field.Name} = {GetReadExpression(field)};";
                var condition = ElementConditionExpression(field, false);
                AppendConditional(builder, condition, 12, assignment);
            }
            builder.AppendLine($"            packet.{repeated.Name}[recordIndex] = tile;");
            builder.AppendLine("        }");
        }
    }

    private static void AppendElementFlagLocals(StringBuilder builder, IReadOnlyList<PacketGraphField> fields, int indent)
    {
        foreach (var field in fields.Where(static field => field.WirePrimitive == PacketWirePrimitive.BitsByte))
            builder.AppendLine($"{new string(' ', indent)}var tile{field.Name}Value = (byte)tile.{field.Name};");
    }

    private static string? ElementConditionExpression(PacketGraphField field, bool useLocalFlags)
    {
        if (field.Conditions.Count == 0) return null;
        return string.Join(" && ", field.Conditions.Select(condition => useLocalFlags
            ? $"(tile{condition.SourceFieldName}Value & 0x{1 << condition.BitIndex:X2}) != 0"
            : $"tile.{condition.SourceFieldName}[{condition.BitIndex}]"));
    }

    private static void AppendFlagLocals(StringBuilder builder, IReadOnlyList<PacketGraphField> fields, int indent)
    {
        foreach (var field in fields.Where(static field => field.WirePrimitive == PacketWirePrimitive.BitsByte))
        {
            var condition = ConditionExpression(field, useLocalFlags: true);
            var expression = condition is null ? $"(byte)packet.{field.Name}" : $"{condition} ? (byte)packet.{field.Name} : (byte)0";
            builder.AppendLine($"{new string(' ', indent)}var {FlagVariable(field.Name)} = {expression};");
        }
    }

    private static void AppendConditional(StringBuilder builder, string? condition, int indent, string statement)
    {
        var whitespace = new string(' ', indent);
        if (condition is null)
        {
            builder.AppendLine($"{whitespace}{statement}");
            return;
        }
        builder.AppendLine($"{whitespace}if ({condition})");
        builder.AppendLine($"{whitespace}{{");
        builder.AppendLine($"{whitespace}    {statement}");
        builder.AppendLine($"{whitespace}}}");
    }

    private static string? ConditionExpression(PacketGraphField field, bool useLocalFlags)
    {
        if (field.Conditions.Count == 0) return null;
        return string.Join(" && ", field.Conditions.Select(condition => useLocalFlags
            ? $"({FlagVariable(condition.SourceFieldName)} & 0x{1 << condition.BitIndex:X2}) != 0"
            : $"packet.{condition.SourceFieldName}[{condition.BitIndex}]"));
    }

    private static string FlagVariable(string name) => char.ToLowerInvariant(name[0]) + name[1..] + "Value";

    private static string GetGeneratedBaseName(PacketGraphManifest manifest)
    {
        var messageId = manifest.MessageId.ToString(System.Globalization.CultureInfo.InvariantCulture);
        return manifest.RuntimePacketType.Name.EndsWith(messageId, StringComparison.Ordinal)
            ? manifest.RuntimePacketType.Name
            : manifest.RuntimePacketType.Name + messageId;
    }

    private static string GetWriteStatement(PacketGraphField field, string target = "packet")
    {
        var value = Nullable.GetUnderlyingType(field.ValueType) is null ? $"{target}.{field.Name}" : $"{target}.{field.Name}.GetValueOrDefault()";
        return field.WirePrimitive switch
        {
            PacketWirePrimitive.Byte => $"WriteByte(destination, ref offset, {value});",
            PacketWirePrimitive.BitsByte => $"WriteByte(destination, ref offset, (byte){value});",
            PacketWirePrimitive.Boolean => $"WriteBoolean(destination, ref offset, {value});",
            PacketWirePrimitive.Int16 => $"WriteInt16(destination, ref offset, {value});",
            PacketWirePrimitive.UInt16 => $"WriteUInt16(destination, ref offset, {value});",
            PacketWirePrimitive.UInt32 => $"WriteUInt32(destination, ref offset, {value});",
            PacketWirePrimitive.Single => $"WriteSingle(destination, ref offset, {value});",
            PacketWirePrimitive.Vector2 => $"WriteVector2(destination, ref offset, {value});",
            _ => throw new NotSupportedException($"Graph field '{field.Name}' has unsupported wire primitive '{field.WirePrimitive}'.")
        };
    }

    private static string GetReadExpression(PacketGraphField field) => field.WirePrimitive switch
    {
        PacketWirePrimitive.Byte => "ReadByte(source, ref offset)",
        PacketWirePrimitive.BitsByte => "(global::Terraria.NetWork.Core.Protocol.BitsByte)ReadByte(source, ref offset)",
        PacketWirePrimitive.Boolean => "ReadBoolean(source, ref offset)",
        PacketWirePrimitive.Int16 => "ReadInt16(source, ref offset)",
        PacketWirePrimitive.UInt16 => "ReadUInt16(source, ref offset)",
        PacketWirePrimitive.UInt32 => "ReadUInt32(source, ref offset)",
        PacketWirePrimitive.Single => "ReadSingle(source, ref offset)",
        PacketWirePrimitive.Vector2 => "ReadVector2(source, ref offset)",
        _ => throw new NotSupportedException($"Graph field '{field.Name}' has unsupported wire primitive '{field.WirePrimitive}'.")
    };

    private static void AppendPrimitiveHelpers(StringBuilder builder)
    {
        builder.AppendLine("    private static void EnsureAvailable(global::System.ReadOnlySpan<byte> source, int offset, int length) { if ((uint)offset > (uint)source.Length || source.Length - offset < length) throw new global::System.IO.InvalidDataException(\"Packet payload was truncated.\"); }");
        builder.AppendLine("    private static void WriteByte(global::System.Span<byte> destination, ref int offset, byte value) => destination[offset++] = value;");
        builder.AppendLine("    private static byte ReadByte(global::System.ReadOnlySpan<byte> source, ref int offset) { EnsureAvailable(source, offset, 1); return source[offset++]; }");
        builder.AppendLine("    private static void WriteInt16(global::System.Span<byte> destination, ref int offset, short value) { global::System.Buffers.Binary.BinaryPrimitives.WriteInt16LittleEndian(destination.Slice(offset, 2), value); offset += 2; }");
        builder.AppendLine("    private static short ReadInt16(global::System.ReadOnlySpan<byte> source, ref int offset) { EnsureAvailable(source, offset, 2); var value = global::System.Buffers.Binary.BinaryPrimitives.ReadInt16LittleEndian(source.Slice(offset, 2)); offset += 2; return value; }");
        builder.AppendLine("    private static void WriteUInt16(global::System.Span<byte> destination, ref int offset, ushort value) { global::System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(destination.Slice(offset, 2), value); offset += 2; }");
        builder.AppendLine("    private static ushort ReadUInt16(global::System.ReadOnlySpan<byte> source, ref int offset) { EnsureAvailable(source, offset, 2); var value = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source.Slice(offset, 2)); offset += 2; return value; }");
        builder.AppendLine("    private static void WriteUInt32(global::System.Span<byte> destination, ref int offset, uint value) { global::System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(destination.Slice(offset, 4), value); offset += 4; }");
        builder.AppendLine("    private static uint ReadUInt32(global::System.ReadOnlySpan<byte> source, ref int offset) { EnsureAvailable(source, offset, 4); var value = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(source.Slice(offset, 4)); offset += 4; return value; }");
        builder.AppendLine("    private static void WriteSingle(global::System.Span<byte> destination, ref int offset, float value) { global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(destination.Slice(offset, 4), global::System.BitConverter.SingleToInt32Bits(value)); offset += 4; }");
        builder.AppendLine("    private static float ReadSingle(global::System.ReadOnlySpan<byte> source, ref int offset) { EnsureAvailable(source, offset, 4); var value = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(offset, 4)); offset += 4; return global::System.BitConverter.Int32BitsToSingle(value); }");
        builder.AppendLine("    private static void WriteBoolean(global::System.Span<byte> destination, ref int offset, bool value) => destination[offset++] = value ? (byte)1 : (byte)0;");
        builder.AppendLine("    private static bool ReadBoolean(global::System.ReadOnlySpan<byte> source, ref int offset) => ReadByte(source, ref offset) != 0;");
        builder.AppendLine("    private static void WriteVector2(global::System.Span<byte> destination, ref int offset, global::System.Numerics.Vector2 value) { WriteSingle(destination, ref offset, value.X); WriteSingle(destination, ref offset, value.Y); }");
        builder.AppendLine("    private static global::System.Numerics.Vector2 ReadVector2(global::System.ReadOnlySpan<byte> source, ref int offset) => new(ReadSingle(source, ref offset), ReadSingle(source, ref offset));");
    }
}
